### PR TITLE
Added support for transparency in indexed PNG images

### PR DESCRIPTION
**Pull request by cheba**
Solves #783

Here's how `palette-8.png` (from the supplied test case) looks like in the resulting document.

screen shot 2015-11-21 at 11 12 46 pm

### CODE REVIEW

**Comment by packetmonkey** [comment]
Nice! In order to get the test suite passing, do we need to just remove the spec that was ensuring we raised an exception for palleted PNG files? Also I think you left a [puts](https://github.com/prawnpdf/prawn/pull/920/files#diff-857d67def6a8ff6448b08d3211b367c0R157) in the specs, we should remove that before merging.

**Comment by cheba** [comment]
@packetmonkey My bad. Fixed specs, removed `puts`, and added a Changelog entry.

**Comment by danielgrippi** [comment]
this fixes an issue i've been seeing on my end.  when can we expect to see this merged?

**Comment by sublimecoder** [comment]
This would fix and issue I have. When can this be merged?

**Comment by packetmonkey** [comment]
@cheba Strangely master is now broken in Travis, I re-ran the build and it looks still broken after merging this and it bundles locally correctly. Can you check this out to see if we broke something with this PR?

**Pull request merged**
