### PR TITLE
fix #1178

### LINKED ISSUE #1178: Missing elements on page when svg is present - regression bug in v2.3.0
Hi all,

I don't know if there is already an opened issue for this.
If I add the svg provided below to the page, the svg itself and other elements are not rendered anymore.
In v2.2.2 they are rendered, in v2.3.0 not.
In Firefox the preview is fine, but once I download the file it's missing the elements.

Here my Gemfile/Gemfile.lock with relevant changes:

```
 # PDF generation
-gem 'prawn', '2.3.0'
+gem 'prawn', '~> 2.2.2'
 gem 'prawn_rails', '0.0.11'
 gem 'prawn-svg', '0.30.0'
 gem 'prawn-table', '0.2.2'
diff --git a/Gemfile.lock b/Gemfile.lock
index 3c3457e85..d865c6597 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -352,13 +352,13 @@ GEM
-    pdf-core (0.8.1)
+    pdf-core (0.7.0)
 
 # PDF generation
-gem 'prawn', '2.3.0'
+gem 'prawn', '~> 2.2.2'
 gem 'prawn_rails', '0.0.11'
 gem 'prawn-svg', '0.30.0'
 gem 'prawn-table', '0.2.2'
diff --git a/Gemfile.lock b/Gemfile.lock
index 3c3457e85..d865c6597 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -352,13 +352,13 @@ GEM
-    pdf-core (0.8.1)
+    pdf-core (0.7.0)
-    prawn (2.3.0)
-      pdf-core (~> 0.8.1)
-      ttfunk (~> 1.6)
+    prawn (2.2.2)
+      pdf-core (~> 0.7.0)
+      ttfunk (~> 1.5)
     prawn-svg (0.30.0)
       css_parser (~> 1.6)
       prawn (>= 0.11.1, < 3)
@@ -637,7 +637,7 @@ DEPENDENCIES 
-  prawn (= 2.3.0)
+  prawn (~> 2.2.2)
   prawn-svg (= 0.30.0)
   prawn-table (= 0.2.2)
```

SVG file:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://creativecommons.org/ns#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" height="559.87994" width="311.81097" version="1.1" viewBox="0 0 311.81098 559.87992" id="svg2" inkscape:version="0.91 r13725" sodipodi:docname="touch-keypad-vertical.svg">
  <metadata id="metadata294">
    <rdf:RDF>
      <cc:Work rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <defs id="defs292" />
  <sodipodi:namedview pagecolor="#ffffff" bordercolor="#666666" borderopacity="1" objecttolerance="10" gridtolerance="10" guidetolerance="10" inkscape:pageopacity="0" inkscape:pageshadow="2" inkscape:window-width="1871" inkscape:window-height="1056" id="namedview290" showgrid="false" fit-margin-top="0" fit-margin-left="0" fit-margin-right="0" fit-margin-bottom="0" inkscape:zoom="0.42154899" inkscape:cx="155.90504" inkscape:cy="279.96059" inkscape:window-x="49" inkscape:window-y="24" inkscape:window-maximized="1" inkscape:current-layer="svg2" />
  <g transform="translate(0.50003687,-493.03317)" id="g4">
    <g transform="matrix(0.99680604,0,0,0.99821697,-0.00159556,1.890457)" id="g6">
      <path d="M 0,513.78 0,1031.1" id="path8" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 21.26,492.52 269.29,0" id="path10" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 311.81,513.78 0,517.32" id="path12" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 21.26,1052.4 269.29,0" id="path14" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="M 311.81,513.78 A 21.26,21.26 0 0 0 290.55,492.52" id="path16" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="M 21.26,492.52 A 21.26,21.26 0 0 0 0,513.78" id="path18" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 0,1031.1 a 21.26,21.26 0 0 0 21.26,21.3" id="path20" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 290.55,1052.4 a 21.26,21.26 0 0 0 21.26,-21.3" id="path22" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 74.409,960.24 0,63.76" id="path24" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 237.4,960.24 0,63.76" id="path26" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 74.409,1024 162.991,0" id="path28" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 74.409,960.24 162.991,0" id="path30" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 129.33,933.66 0,21.26" id="path32" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 164.76,933.66 0,21.26" id="path34" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 200.2,933.66 0,21.26" id="path36" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 235.63,933.66 0,21.26" id="path38" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 76.181,933.66 0,21.26" id="path40" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 76.181,954.92 159.449,0" id="path42" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 76.181,944.29 159.449,0" id="path44" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 76.181,933.66 159.449,0" id="path46" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 235.63,954.92 -35.43,0" id="path48" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 217.91,954.92 0,-10.63" id="path50" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 200.2,954.92 -35.44,0" id="path52" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 182.48,954.92 0,-10.63" id="path54" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 164.76,954.92 -35.43,0" id="path56" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 147.05,954.92 0,-10.63" id="path58" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 111.61,954.92 0,-10.63" id="path60" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 93.898,954.92 0,-10.63" id="path62" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 69.094,550.1 0,31.89" id="path64" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 95.669,550.1 0,31.89" id="path66" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 95.669,550.1 a 13.2875,13.2875 0 0 0 -26.575,0" id="path68" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 69.094,581.99 a 13.2875,13.2875 0 0 0 26.575,0" id="path70" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 287.01,543.9 a 19.49,19.49 0 1 0 -38.98,0 19.49,19.49 0 1 0 38.98,0 z" id="path72" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 104.15,917.11 z m -3.59,2.94 z" id="path74" inkscape:connector-curvature="0" style="fill:#000000" />
      <path d="m 104.15,917.11 c 0,0 -3.59,2.94 -3.59,2.94 -0.55,-0.18 -1.03,-0.46 -1.438,-0.85 -0.408,-0.39 -0.676,-0.83 -0.806,-1.33 0,0 -2.806,1.6 -2.806,1.6 -0.11,0.06 -0.299,0.12 -0.567,0.17 -0.259,0.07 -0.478,0.11 -0.657,0.11 -2.16,0 -3.946,-0.74 -5.359,-2.22 -1.403,-1.49 -2.105,-3.55 -2.105,-6.18 0,-2.51 0.732,-4.58 2.195,-6.2 1.463,-1.63 3.328,-2.45 5.597,-2.45 0.906,0 1.752,0.18 2.538,0.54 0.786,0.36 1.303,0.68 1.553,0.96 0,0 2.595,-0.95 2.595,-0.95 0,0 0.91,0.27 0.91,0.27 l 0,10.24 c 0,0.9 0.16,1.61 0.47,2.14 0.31,0.53 0.81,0.93 1.47,1.21 z" id="path76" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 97.839,914.87 0,-7 c -0.299,-0.37 -0.692,-0.68 -1.18,-0.94 -0.477,-0.27 -1.065,-0.41 -1.761,-0.41 -1.005,0 -1.841,0.37 -2.508,1.11 -0.657,0.73 -0.985,1.93 -0.985,3.63 0,1.34 0.308,2.42 0.926,3.24 0.616,0.8 1.482,1.2 2.597,1.2 0.637,0 1.234,-0.1 1.791,-0.29 0.557,-0.2 0.93,-0.38 1.12,-0.54 z" id="path78" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 116.92,914.63 0,-0.75" id="path80" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 107.33,917.38 z m 9.86,1.09 z" id="path82" inkscape:connector-curvature="0" style="fill:#000000" />
      <path d="m 121.41,913.88 0,5.69 -3.48,0 c 0,0 -0.98,-1.46 -0.98,-1.46 0,0 -2.41,1.31 -2.41,1.31 -0.2,0.11 -0.49,0.19 -0.86,0.24 -0.38,0.06 -0.71,0.09 -0.99,0.09 -2.35,0 -4.13,-0.79 -5.36,-2.37 -0.77,-1.01 -1.3,-2.17 -1.58,-3.5" id="path84" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 105.75,913.88 c -0.17,-0.77 -0.25,-1.59 -0.25,-2.46" id="path86" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 105.5,911.42 c -0.01,-2.59 0.72,-4.65 2.19,-6.18" id="path88" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 107.69,905.24 c 1.48,-1.53 3.44,-2.3 5.87,-2.3" id="path90" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 113.56,902.94 c 0.69,0 1.31,0.06 1.83,0.17" id="path92" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 115.39,903.11 c 0.53,0.11 1.04,0.3 1.53,0.58" id="path94" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 116.92,903.69 0,-7.05" id="path96" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 116.92,896.64 4.49,0" id="path98" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 121.41,896.64 0,17.24" id="path100" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 110.59,913.88 c 0.13,0.29 0.28,0.54 0.46,0.76 0.66,0.8 1.54,1.2 2.66,1.2 0.71,0 1.34,-0.12 1.88,-0.36 0.54,-0.24 0.99,-0.52 1.33,-0.85 l 0,-7.08 c -0.25,-0.3 -0.67,-0.57 -1.24,-0.79 -0.58,-0.23 -1.21,-0.34 -1.88,-0.34 -1.26,0 -2.19,0.37 -2.81,1.1 -0.61,0.73 -0.91,1.89 -0.91,3.48 0,1.17 0.17,2.13 0.51,2.88" id="path102" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="M 145.67,919.57 Z" id="path104" inkscape:connector-curvature="0" style="fill:#000000" />
      <path d="m 145.67,919.57 -4.56,0 0,-10.08 c 0,-0.58 -0.21,-1.1 -0.62,-1.55 -0.42,-0.46 -1.06,-0.68 -1.93,-0.68 -0.83,0 -1.52,0.17 -2.07,0.52 -0.56,0.34 -1,0.65 -1.33,0.95 l 0,10.84 -4.57,0 0,-16.05 c 0,0 4.57,-0.32 4.57,-0.32 l 0,1.56 c 0,0 1.89,-1.09 1.89,-1.09 0.57,-0.33 1.15,-0.56 1.73,-0.7 0.6,-0.15 1.19,-0.22 1.78,-0.22 1.58,0 2.83,0.49 3.73,1.47 0.92,0.98 1.38,2.27 1.38,3.87 l 0,11.48 z" id="path106" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 150.47,917.53 z m 14.54,-3.52 z" id="path108" inkscape:connector-curvature="0" style="fill:#000000" />
      <path d="m 153.23,909.12 c -0.17,0.63 -0.25,1.34 -0.25,2.12 0,1.04 0.2,1.97 0.61,2.77 0.13,0.27 0.29,0.53 0.46,0.77 0.72,0.97 1.68,1.46 2.89,1.46 1.34,0 2.3,-0.39 2.88,-1.18 0.21,-0.28 0.38,-0.63 0.52,-1.05" id="path110" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 165.01,914.01 c -0.35,1.39 -1,2.56 -1.94,3.53 -1.51,1.56 -3.59,2.34 -6.22,2.34 -2.84,0 -4.96,-0.78 -6.38,-2.35 -0.87,-0.98 -1.47,-2.15 -1.81,-3.52" id="path112" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 148.66,914.01 c -0.2,-0.84 -0.31,-1.77 -0.31,-2.77 0,-0.74 0.08,-1.44 0.22,-2.12" id="path114" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 165.16,909.12 c 0.12,0.67 0.18,1.37 0.18,2.12 0,1 -0.11,1.93 -0.33,2.77" id="path116" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 160.34,914.01 c 0.24,-0.73 0.36,-1.65 0.36,-2.77" id="path118" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 160.7,911.24 c 0,-0.75 -0.12,-1.46 -0.35,-2.12" id="path120" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 148.57,909.12 c 0.33,-1.49 1.02,-2.82 2.07,-3.98 1.52,-1.7 3.59,-2.54 6.21,-2.54 2.62,0 4.69,0.78 6.21,2.34 1.09,1.12 1.79,2.51 2.1,4.18" id="path122" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 160.35,909.12 c -0.17,-0.48 -0.39,-0.93 -0.68,-1.36" id="path124" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 159.67,907.76 c -0.68,-1.01 -1.62,-1.52 -2.82,-1.52 -1.39,0 -2.38,0.46 -2.97,1.39" id="path126" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 153.88,907.63 c -0.29,0.43 -0.5,0.93 -0.65,1.49" id="path128" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="M 175.76,916.78 Z" id="path130" inkscape:connector-curvature="0" style="fill:#000000" />
      <path d="m 175.76,916.78 c 0,0 -3.31,3.12 -3.31,3.12 -1.38,-0.57 -2.41,-1.39 -3.09,-2.48 -0.69,-1.09 -1.03,-2.4 -1.03,-3.91 l 0,-7.02 -1.53,0 0,-2.98 1.53,0 0,-5.29 c 0,0 4.56,-0.32 4.56,-0.32 l 0,5.62 2.39,0 0,2.96 -2.39,0 0,5.73 c 0,1.15 0.26,2.1 0.78,2.85 0.52,0.76 1.21,1.33 2.09,1.72 z" id="path132" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="M 194.12,917.11 Z" id="path134" inkscape:connector-curvature="0" style="fill:#000000" />
      <path d="m 194.12,917.11 c 0,0 -3.6,2.94 -3.6,2.94 -0.55,-0.18 -1.02,-0.46 -1.43,-0.85 -0.41,-0.39 -0.68,-0.83 -0.81,-1.33 0,0 -2.8,1.6 -2.8,1.6 -0.11,0.06 -0.3,0.12 -0.57,0.17 -0.26,0.07 -0.48,0.11 -0.66,0.11 -2.16,0 -3.94,-0.74 -5.36,-2.22 -1.4,-1.49 -2.1,-3.55 -2.1,-6.18 0,-2.51 0.73,-4.58 2.19,-6.2 1.47,-1.63 3.33,-2.45 5.6,-2.45 0.91,0 1.75,0.18 2.54,0.54 0.79,0.36 1.3,0.68 1.55,0.96 0,0 2.6,-0.95 2.6,-0.95 0,0 0.91,0.27 0.91,0.27 l 0,10.24 c 0,0.9 0.15,1.61 0.46,2.14 0.32,0.53 0.81,0.93 1.48,1.21 z" id="path136" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 187.81,914.87 0,-7 c -0.3,-0.37 -0.7,-0.68 -1.18,-0.94 -0.48,-0.27 -1.07,-0.41 -1.77,-0.41 -1,0 -1.84,0.37 -2.5,1.11 -0.66,0.73 -0.99,1.93 -0.99,3.63 0,1.34 0.31,2.42 0.93,3.24 0.61,0.8 1.48,1.2 2.59,1.2 0.64,0 1.24,-0.1 1.8,-0.29 0.55,-0.2 0.93,-0.38 1.12,-0.54 z" id="path138" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="M 221.51,919.57 Z" id="path140" inkscape:connector-curvature="0" style="fill:#000000" />
      <path d="m 221.51,919.57 -4.54,0 0,-10.08 c 0,-0.58 -0.2,-1.1 -0.61,-1.55 -0.4,-0.46 -1.03,-0.68 -1.89,-0.68 -0.71,0 -1.34,0.13 -1.9,0.41 -0.56,0.27 -1.03,0.63 -1.4,1.06 l 0,10.84 -4.54,0 0,-10.08 c 0,-0.58 -0.21,-1.1 -0.61,-1.55 -0.4,-0.46 -1.03,-0.68 -1.9,-0.68 -0.82,0 -1.5,0.16 -2.06,0.5 -0.56,0.33 -0.96,0.65 -1.22,0.97 l 0,10.84 -4.54,0 0,-16.05 c 0,0 4.54,-0.32 4.54,-0.32 l 0,1.56 c 0,0 1.77,-1.09 1.77,-1.09 0.59,-0.36 1.17,-0.6 1.74,-0.73 0.56,-0.13 1.14,-0.19 1.73,-0.19 1.05,0 1.95,0.22 2.7,0.65 0.74,0.43 1.32,1.02 1.72,1.78 0,0 2.46,-1.51 2.46,-1.51 0.5,-0.31 1.04,-0.53 1.63,-0.68 0.58,-0.16 1.19,-0.24 1.83,-0.24 1.58,0 2.83,0.49 3.73,1.47 0.91,0.98 1.36,2.27 1.36,3.87 l 0,11.48 z" id="path142" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 76.181,1018.7 0,-53.15" id="path144" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 235.63,1018.7 -159.449,0" id="path146" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 235.63,969.09 -159.449,0" id="path148" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 235.63,993.9 -159.449,0" id="path150" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 111.61,993.9 0,-24.81" id="path152" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 129.33,969.09 0,24.81" id="path154" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 93.898,969.09 0,24.81" id="path156" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 93.898,993.9 0,-6.2" id="path158" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 147.05,993.9 0,-24.81" id="path160" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 146.16,970.33 0,22.33" id="path162" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 146.16,992.66 -15.94,0" id="path164" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 130.22,992.66 0,-11.16" id="path166" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 130.22,981.5 0,-11.17" id="path168" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 130.22,970.33 15.94,0" id="path170" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 128.44,992.66 -15.94,0" id="path172" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 128.44,970.33 0,22.33" id="path174" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 112.5,992.66 0,-22.33" id="path176" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 112.5,970.33 15.94,0" id="path178" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 94.783,970.33 15.947,0" id="path180" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 94.783,992.66 0,-22.33" id="path182" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 110.73,992.66 -15.947,0" id="path184" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 110.73,970.33 0,22.33" id="path186" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 77.067,970.33 15.945,0" id="path188" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 93.012,970.33 0,22.33" id="path190" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 93.012,992.66 -15.945,0" id="path192" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 77.067,992.66 0,-22.33" id="path194" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 235.63,965.55 -159.449,0" id="path196" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 147.05,969.09 0,24.81" id="path198" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 163.88,970.33 0,22.33" id="path200" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 163.88,992.66 -15.95,0" id="path202" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 147.93,992.66 0,-11.16" id="path204" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 147.93,981.5 0,-11.17" id="path206" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 147.93,970.33 15.95,0" id="path208" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 164.76,969.09 0,24.81" id="path210" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 181.59,970.33 0,22.33" id="path212" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 181.59,992.66 -15.94,0" id="path214" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 165.65,992.66 0,-11.16" id="path216" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 165.65,981.5 0,-11.17" id="path218" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 165.65,970.33 15.94,0" id="path220" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 182.48,969.09 0,24.81" id="path222" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 199.31,970.33 0,22.33" id="path224" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 199.31,992.66 -15.94,0" id="path226" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 183.37,992.66 0,-11.16" id="path228" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 183.37,981.5 0,-11.17" id="path230" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 183.37,970.33 15.94,0" id="path232" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 200.2,969.09 0,24.81" id="path234" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 217.03,970.33 0,22.33" id="path236" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 217.03,992.66 -15.95,0" id="path238" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 201.08,992.66 0,-11.16" id="path240" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 201.08,981.5 0,-11.17" id="path242" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 201.08,970.33 15.95,0" id="path244" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 217.91,969.09 0,24.81" id="path246" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 234.74,970.33 0,22.33" id="path248" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 234.74,992.66 -15.94,0" id="path250" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 218.8,992.66 0,-11.16" id="path252" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 218.8,981.5 0,-11.17" id="path254" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 218.8,970.33 15.94,0" id="path256" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 235.63,1018.7 0,-53.15" id="path258" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 285.24,543.9 a 17.72,17.72 0 1 0 -35.44,0 17.72,17.72 0 1 0 35.44,0 z" id="path260" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
      <path d="m 268.65,543.9 a 1.13,1.13 0 1 0 -2.26,0 1.13,1.13 0 1 0 2.26,0 z" id="path262" inkscape:connector-curvature="0" style="fill:none;stroke:#000000" />
    </g>
  </g>
  <g transform="translate(0.50003687,-493.03317)" id="g264" style="fill:#333333">
    <path d="M 1416.9,386.47 Z" id="path266" inkscape:connector-curvature="0" />
    <path d="M 1481.5,386.47 Z" id="path268" inkscape:connector-curvature="0" />
    <path d="M 1352.5,386.41 Z" id="path270" inkscape:connector-curvature="0" />
    <path d="M 1416.9,193.93 Z" id="path272" inkscape:connector-curvature="0" />
    <path d="M 1394,217.52 Z" id="path274" inkscape:connector-curvature="0" />
    <path d="M 1481.5,194.46 Z" id="path276" inkscape:connector-curvature="0" />
    <path d="M 697.5,386.47 Z" id="path278" inkscape:connector-curvature="0" />
    <path d="M 762.07,386.47 Z" id="path280" inkscape:connector-curvature="0" />
    <path d="M 633.05,386.41 Z" id="path282" inkscape:connector-curvature="0" />
    <path d="M 697.5,193.93 Z" id="path284" inkscape:connector-curvature="0" />
    <path d="M 674.57,217.52 Z" id="path286" inkscape:connector-curvature="0" />
    <path d="M 762.07,194.46 Z" id="path288" inkscape:connector-curvature="0" />
  </g>
</svg>
```

Thank you for your support!

### PR DESCRIPTION
**Pull request by afdev82**
This PR fixes the issue #1178

### CODE REVIEW

**Comment by pointlessone** [comment]
Hello Antonio,

Thank you for your contribution.

Could you please rebase your branch on top of current master, give the commit a bit more descriptive title and add some tests?

**Comment by afdev82** [comment]
Hi, I could rebase, I was thinking about a title and maybe something like "use format instead of round in transformation_matrix method, fixes #1178"?
About the tests, I don't know how to write them for this project, I would need to dig in and I don't have so much time at the moment. Some suggestions would be great, so I can try to do that when I find some time.

**Comment by pointlessone** [comment]
Maybe leave it for now. I'll try and find some time this week to tend to this issue.

**Comment by pointlessone** [comment]
Thank you for your contribution.

This issue has been fixed in the latest Prawn release.

**Pull request closed without merging**
