### PR TITLE
Syntax update for manual

### PR DESCRIPTION
**Pull request by wingfire**
The patch replaces the old hash syntax (:symbol => value) with the new syntax (symbol: value) being implementented with ruby 1.9.2 in the manual.

### CODE REVIEW

**Comment by packetmonkey** [comment]
I'm good with this change in principal. I do need a few changes to be made first

- Please fix the failing rubocop test
- Please add an entry to the change log documenting that we are using the new hash syntax in the manual
- Currently the `HashSyntax` rubocop cop is disabled. Please configure it to be enabled for the manual directory.

Once that is done I'll pull down the branch and ensure that the manual still builds and really deep dive on the PR, but that should be all the changes that need to be made.

**Comment by wingfire** [comment]
Hi, i fixed the rubocop test, enhanced the change log and enabled rubocop HashSyntax tests for manual directory. Anything else i have to do for the pull request?

**Comment by packetmonkey** [comment]
Can you please rebase your branch so that it can merge into master without a conflict? Then we should be able to review this change and get it in.

**Comment by wingfire** [comment]
done

**Comment by wingfire** [comment]
Any thing else i can do?

**Comment by packetmonkey** [comment]
I looked over the PR and it looks good, I also checked it out locally and successfully built the manual. Can you please do a manual comparison between your generated manual and compare it to the [currently public manual](http://prawnpdf.org/manual.pdf) to make sure nothing looks totally off? Normally that is done during the release process and takes about 20 minutes to just compare page by page to make sure nothing looks totally wrong.

Once that last visual check is done this is good to merge.

**Comment by pointlessone** [comment]
@wingfire Thank you for your contribution.

This issue has been addressed in master. I will close this PR now. Feel free to reopen if you feel this PR is still relevant.

**Pull request closed without merging**
