### PR TITLE
Test on Ruby 2.6 on Travis CI

### PR DESCRIPTION
**Pull request by aried3r**
I saw that this gem is being tested in the lowest and highest patch version of a Ruby release so I did the same with Ruby 2.6. But might I suggest only testing on the very latest patch version? It would greatly reduce test runs and I don't think there is much of a benefit of doing this. WDYT?

### CODE REVIEW

**Comment by pointlessone** [comment]
Hi, Anton. Thanks for the contribution.

Historically, there were breaking changes in tiny ("patch" in SemVer vocabulary) releases of Ruby. Generally, builds are ran in parallel. Even though there's some overhead it's far from double. In that regards dropping JRuby would be much significant gain but we're not doing it.

While you're at it, I wonder if you have a bit more time to contribute the same change to PDFCore and TTFunk?

**Comment by aried3r** [comment]
> While you're at it, I wonder if you have a bit more time to contribute the same change to PDFCore and TTFunk?

I'll certainly try! On that note, do you think there'll be a new release of prawn soon?

**Comment by pointlessone** [comment]
There definitely will be a release at some point but probably not "soon" in a conventional meaning. Soon™.

**Comment by aried3r** [comment]
> Soon™

Haha, fair enough. I think there's [quite some people](https://github.com/prawnpdf/prawn/issues/1052) waiting for it. I don't really know much about the internals of prawn, but is there anything you want to do before the next release that's keeping it from being released?

Test pass, so I'd even use a `.pre` version if available on RubyGems :)

**Comment by pointlessone** [comment]
I'm aware about that issue.

I want to update code style. Basically, update Rubocop dep and make it happy. And there's a big feature coming to TTFunk. These two things need to happen for the next release of all three gems. The feature takes some time because it's big and complex. Rubocop though can be done by someone else. I intend to do it myself but life gets priority.

**Pull request merged**
