### PR TITLE
Convert specs to RSpec 2.14.8 syntax with Transpec

### PR DESCRIPTION
**Pull request by wpolicarpo**
This conversion is done by Transpec 3.1.0 with the following command:
    transpec

* 1013 conversions
    from: obj.should
      to: expect(obj).to

* 873 conversions
    from: == expected
      to: eq(expected)

* 40 conversions
    from: obj.should_not
      to: expect(obj).not_to

* 39 conversions
    from: lambda { }.should
      to: expect { }.to

* 25 conversions
    from: =~ /pattern/
      to: match(/pattern/)

* 4 conversions
    from: <= expected
      to: be <= expected

* 3 conversions
    from: obj.should have(n).entries
      to: expect(obj.entries.size).to eq(n)

* 2 conversions
    from: collection.should have(n).items
      to: expect(collection.size).to eq(n)

* 1 conversion
    from: < expected
      to: be < expected

* 1 conversion
    from: > expected
      to: be > expected

* 1 conversion
    from: >= expected
      to: be >= expected

* 1 conversion
    from: lambda { }.should_not
      to: expect { }.not_to

For more details: https://github.com/yujinakayama/transpec#supported-conversions

### CODE REVIEW

**Comment by packetmonkey** [comment]
Thanks for this! because of how important the spec suite is I'm going to very carefully look over the diff to make sure I don't see anything weird, but in concept I have no problem merging this once I have had a chance to dig though it.

**Comment by wpolicarpo** [comment]
Take your time @packetmonkey. Especially because I had to fix a lot of rubocop offenses after conversion, it's important to see if I didn't break something up.

**Comment by packetmonkey** [comment]
Do you think it would be possible to split this up into smaller PRs? That way we could review and merge them into smaller chunks instead of waiting until a giant review is done and possibly increase the risk of missing something.

**Comment by wpolicarpo** [comment]
Any suggestions on how to organize that split? Maybe I can do that.

**Comment by packetmonkey** [comment]
I was thinking per-file maybe, but really the problem is I can't revirew them all at once. but I don't have to.
I created a list for every file in the PR and as they get reviewed they can be marked off. 

I'll keep this list up to date as I go.

- [ ] spec/annotations_spec.rb
- [ ] spec/bounding_box_spec.rb
- [ ] spec/column_box_spec.rb
- [ ] spec/destinations_spec.rb
- [ ] spec/document_spec.rb
- [ ] spec/font_metric_cache_spec.rb
- [ ] spec/font_spec.rb
- [ ] spec/formatted_text_arranger_spec.rb
- [ ] spec/formatted_text_box_spec.rb
- [ ] spec/formatted_text_fragment_spec.rb
- [ ] spec/graphics_spec.rb
- [ ] spec/grid_spec.rb
- [ ] spec/image_handler_spec.rb
- [ ] spec/images_spec.rb
- [ ] spec/inline_formatted_text_parser_spec.rb
- [ ] spec/jpg_spec.rb
- [ ] spec/line_wrap_spec.rb
- [ ] spec/measurement_units_spec.rb
- [ ] spec/outline_spec.rb
- [ ] spec/png_spec.rb
- [ ] spec/reference_spec.rb
- [ ] spec/repeater_spec.rb
- [ ] spec/security_spec.rb
- [ ] spec/soft_mask_spec.rb
- [ ] spec/span_spec.rb
- [ ] spec/stamp_spec.rb
- [ ] spec/stroke_styles_spec.rb
- [ ] spec/text_at_spec.rb
- [ ] spec/text_box_spec.rb
- [ ] spec/text_rendering_mode_spec.rb
- [ ] spec/text_spacing_spec.rb
- [ ] spec/text_spec.rb
- [ ] spec/text_with_inline_formatting_spec.rb
- [ ] spec/transparency_spec.rb

**Comment by packetmonkey** [comment]
I _finally_ managed to get though this PR. Thank you for opening it and I'm ready to merge it. The spec suite is important and it's helpful to keep it up to the current RSpec best practices.

Sorry it took so long!

Once @practicingruby grants me permissions to modify the Contributors group, you will get commit access to prawn because you had a pull request merged. Here are [the details](https://github.com/prawnpdf/prawn/wiki/Contributor-welcome-notes). Thanks again for helping prawn

**Comment by packetmonkey** [comment]
You have been added to the contributors group, thanks again!

**Comment by wpolicarpo** [comment]
Thanks, @packetmonkey. I hope to contribute more...

**Pull request merged**
