### PR TITLE
Fix reported Rubocop warnings

### PR DESCRIPTION
**Pull request by fidothe**
There were two trivial whitespace issues and one would-prefer-this-approach issue in the specs. This fixes all three

### CODE REVIEW

**Comment by pointlessone** [comment]
Thanks. 👍

**Comment by fidothe** [comment]
#1032 is failing because of the Rubocop warnings this fixes. If this can get merged I can rebase it off master and it'll pass...

**Comment by pointlessone** [comment]
@fidothe Can't you merge after approval?

**Comment by fidothe** [comment]
@pointlessone no - I don't have write access

**Comment by pointlessone** [comment]
@fidothe Weird. Please contact me over email.

**Pull request merged**
