### PR TITLE
resolves #1048 flaw in generating gradient pattern key

### LINKED ISSUE #1048: Wrong gradient attributes occasionally being rendered
I have a document with several small polygon shapes in different colours over many pages. I am experiencing an issue where occasionally a shape is rendered in the wrong colour.

I believe this is caused by collisions in the registry key used to store the gradient as a page resource. The key is created from a digest of the gradient attributes, packed as unsigned 8-bit characters.

## Example

This small example illustrates the issue.

```ruby
Prawn::Document.generate('gradient.pdf') do                                        
  stroke_axis                                                                      
                                                                                   
  # top left solid pink                                                            
  fill_color 'fe00ff'                                                              
  fill_rectangle [150,512], 100, 100                                               
                                                                                   
  # top right gradient pink                                                        
  fill_gradient [256,512], [356,512], 'ffffff', 'fe00ff'                           
  fill_rectangle [256,512], 100, 100                                               
                                                                                   
  # bottom left solid blue                                                         
  fill_color '0000ff'                                                              
  fill_rectangle [150,256], 100, 100                                               
                                                                                   
  # bottom right gradient blue                                                     
  fill_gradient [256,256], [356,256], 'ffffff', '0000ff'                           
  fill_rectangle [256,256], 100, 100                                                                                                                           
end
```
screen shot 2017-11-18 at 22 54 49

The key for the gradient on the bottom right is identical to the previously generated key for the top right gradient and consequently the rectangle uses the old gradient definition.

## Solution

Would it be possible to avoid packing the attributes down to 8-bit values and to also use a SHA2 digest (for a longer key)?

Suggest changing the method in **lib/prawn/graphics/patterns.rb** from:

``` ruby
def gradient_registry_key(gradient)                                                
  _x1, _y1, x2, y2, transformation = gradient_coordinates(gradient)                
                                                                                   
  key = [                                                                          
    gradient.type.to_s,                                                            
    transformation,                                                                
    x2, y2,                                                                        
    gradient.r1 || -1, gradient.r2 || -1,                                          
    gradient.stops.length,                                                         
    gradient.stops.map { |s| [s.position, s.color] }                               
  ].flatten                                                                        
  Digest::SHA1.hexdigest(key.pack('HC*'))                                             
end
```

to:

```ruby
def gradient_registry_key(gradient)                                                
  _x1, _y1, x2, y2, transformation = gradient_coordinates(gradient)                
                                                                                   
  key = [                                                                          
    gradient.type.to_s,                                                            
    transformation,                                                                
    x2, y2,                                                                        
    gradient.r1 || -1, gradient.r2 || -1,                                          
    gradient.stops.length,                                                         
    gradient.stops.map { |s| [s.position, s.color] }                               
  ].flatten                                                                        
  Digest::SHA2.hexdigest key.join(',')                                             
end
```

### PR DESCRIPTION
**Pull request by jacksop**
Packing gradient attributes down to 8-bit values causes collisions when generating the SHA1 digest.

Concatinate the gradient attributes into a string in order to calculate the digest for the key.

### CODE REVIEW

**Comment by jacksop** [comment]
Had an issue with the manual spec. Not sure why the hash has changed 🤔

**Comment by pointlessone** [comment]
I think, gradient IDs changed with this PR. So the manual has changed as well. Make sure those are the only changes.

**Comment by jacksop** [comment]
Produced the manual in both Ruby and JRuby to confirm no unexpected changes. The following is a diff from the Ruby produced pdf.

```diff
--- a/new_man.pdf
+++ b/old_man.pdf
@@ -28295,37 +28295,37 @@ S
 [] 0 d
 10 w
 /Pattern cs
-/SPb2ac70e4092a30e61b731f0ddcce5d2504387e26 scn
+/SPc027eb13458c6a3a5e5bb248c66f0a9bda7e3ae5 scn
 36.0 186.0 100.0 100.0 re
 f
 /Pattern CS
-/SP9bc3d87486885cdd70bcc232bdb8390eb40b3406 SCN
+/SP143b3ff7c833028e87374381ce150c291c83c0a5 SCN
 186.0 186.0 100.0 100.0 re
 S
-/SP88db9f7dce277b8129cdf156cddfc04f1f03f97e scn
-/SPfe1deee7ddb28305363bf0b8499100bb5c6398dc SCN
+/SP1ff2cc60c143e283d45a23e66ec1471a5b7d85cf scn
+/SP4c162120d6599fd9f1e63b83fad681f42ff7e303 SCN
 336.0 186.0 100.0 100.0 re
 b
 q
 1.00000 0.00000 0.00000 1.00000 323.86797 -309.88644 cm
 q
 0.70711 0.70711 -0.70711 0.70711 0.00000 0.00000 cm
-/SPc0f96e6212ed723e20c7902080036d459b015f36 scn
+/SP6f68d2e29b15a5532c23070e22d7bd7c06bc52ee scn
 496.0 196.0 80.0 80.0 re
 f
 Q
 Q
-/SPc45c6ba25edd986cedc8481d02073dc33a93cf0b scn
+/SP8256b94b16aea0a7d1641d75dd5d8e296895f9ae scn
 36.0 36.0 100.0 100.0 re
 f
-/SPeac6fb4ee24b0a4a6337258aaeadc4b81ee57327 SCN
+/SP47d5de4ca76cc74d261d227e82a96e3f6111ff74 SCN
 186.0 36.0 100.0 100.0 re
 S
-/SPfbad10aa6625193155391a3905abf363078813bc SCN
-/SP2e5547f809c03cb6a532e7f1d432ffe3ac3d39f6 scn
+/SP7825f5024162679626a2bc82fa41f9c8145d9c1a SCN
+/SPd26d3d41fe66bcec38ce4b605d8267af56155a59 scn
 336.0 36.0 100.0 100.0 re
 b
-/SP02b2d2a7b384f69b8f0bff4a895a70c84e8b2bd5 scn
+/SPf13c6a82cfdc4418087e761196d8fb506ae16f5d scn
 486.0 36.0 100.0 100.0 re
 f
 1 w
@@ -28354,16 +28354,16 @@ endobj
 /F1.0 17 0 R
 /F3.0 11 0 R
 >>
-/Pattern << /SPb2ac70e4092a30e61b731f0ddcce5d2504387e26 97 0 R
-/SP9bc3d87486885cdd70bcc232bdb8390eb40b3406 100 0 R
-/SP88db9f7dce277b8129cdf156cddfc04f1f03f97e 103 0 R
-/SPfe1deee7ddb28305363bf0b8499100bb5c6398dc 106 0 R
-/SPc0f96e6212ed723e20c7902080036d459b015f36 112 0 R
-/SPc45c6ba25edd986cedc8481d02073dc33a93cf0b 115 0 R
-/SPeac6fb4ee24b0a4a6337258aaeadc4b81ee57327 118 0 R
-/SPfbad10aa6625193155391a3905abf363078813bc 121 0 R
-/SP2e5547f809c03cb6a532e7f1d432ffe3ac3d39f6 124 0 R
-/SP02b2d2a7b384f69b8f0bff4a895a70c84e8b2bd5 127 0 R
+/Pattern << /SPc027eb13458c6a3a5e5bb248c66f0a9bda7e3ae5 97 0 R
+/SP143b3ff7c833028e87374381ce150c291c83c0a5 100 0 R
+/SP1ff2cc60c143e283d45a23e66ec1471a5b7d85cf 103 0 R
+/SP4c162120d6599fd9f1e63b83fad681f42ff7e303 106 0 R
+/SP6f68d2e29b15a5532c23070e22d7bd7c06bc52ee 112 0 R
+/SP8256b94b16aea0a7d1641d75dd5d8e296895f9ae 115 0 R
+/SP47d5de4ca76cc74d261d227e82a96e3f6111ff74 118 0 R
+/SP7825f5024162679626a2bc82fa41f9c8145d9c1a 121 0 R
+/SPd26d3d41fe66bcec38ce4b605d8267af56155a59 124 0 R
+/SPf13c6a82cfdc4418087e761196d8fb506ae16f5d 127 0 R
 >>
 >>
 >>
```

**Comment by pointlessone** [comment]
All changes to the manual seem to be expected.

**Comment by pointlessone** [comment]
Could you please add spec that checks for collision that used to be generated?

**Pull request merged**
