### PR TITLE
raise an exception when align value is not a Symbol

### PR DESCRIPTION
**Pull request by lucianosousa**

### CODE REVIEW

**Comment by pointlessone** [comment]
@lucianosousa Hi! Thank you for your interest in giving back to community!

Could you please give a bit of context for this PR?

**Comment by lucianosousa** [comment]
@pointlessone sure man.
I was trying to align here with `align: 'center'` and the pdf render just broke.
Some rails methods accept both kinds of argument types, eg: https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations.rb#L256
we can do the same here, don't you think?

**Comment by pointlessone** [comment]
Prawn is not a part of the Ruby on Rails framework. We do not quite share an outlook on API design with Rails.

I agree that it's suboptimal to break document rendering. But I think a proper solution here to let the user know what's wrong instead of extending the API. We generally do not accept strings where only a limited number of named options can be accepted and I don't want to diverge from that in this case.

What do you think of an alternative solution? Add an `else` to that `case` that will raise an `ArgumentError` with a descriptive message.

**Comment by lucianosousa** [comment]
@pointlessone cool. better raise an exception then ;)

**Comment by pointlessone** [comment]
@lucianosousa Would you like to change the code in this PR or l it to someone else?

**Comment by lucianosousa** [comment]
@pointlessone sorry the delay. it's here! ;)

**Comment by pointlessone** [comment]
@lucianosousa I would very much prefer if the exception was risen in every unrecognized case not only when it's not a symbol.

**Comment by lucianosousa** [comment]
sorry being late. updated

**Comment by pointlessone** [comment]
NP. Thank you for keeping working on this.

Could you please put the `raise` into `else` branch of the `case` statement to save us extra check?

**Comment by lucianosousa** [comment]
done @pointlessone sorry being late

**Comment by lucianosousa** [comment]
@pointlessone I guess we need merge #1060 first here

**Comment by pointlessone** [comment]
Not sure. That one improves document consistency but I never saw a difference between 2.2 and 2.3+.

**Comment by lucianosousa** [comment]
@pointlessone just merged and passes! :D ready for u

**Comment by pointlessone** [comment]
@lucianosousa Could you please clean up the history a bit?

**Comment by lucianosousa** [comment]
@pointlessone done

**Comment by pointlessone** [comment]
Thank you for your contribution.

**Pull request merged**
